# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       humingxuan
  url:        https://xuan1012.github.io/

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown